jarpath: "1MSS-assembly-0.1.jar"

n_instances_per_param: 30

ctr_methods:
  - nothing
  - lpbound-fast-no-recompute
  - lpbound-fast-no-recompute-filter-row
  - lpbound-recompute
  - lpbound-recompute-filter-row
  - lpbound-recompute-partial-2-filter-row
  - lpbound-recompute-partial-5-filter-row

branch_methods:
  - static
  - dynamic

synth_test_complete: # ["sizeRxsizeC", probably_row_or_col_in_sol_in_pct, timeout]
  - ["20x20", 30, 30]
  - ["25x25", 30, 30]
  - ["50x50", 20, 60]
  - ["50x150", 20, 60]
  - ["300x300", 10, 60]
