jarpath: "1MSS-assembly-0.1.jar"
mippath: "mip/mip.py"

methods:
  - ["original", "static"]
  - ["original-lb", "static"]
  - ["original-lb-fast", "static"]
  - ["fixed-bigm", "static"]
  - ["fixed-bigm", "dynamic"]
  - ["recompute-bigm", "static"]
  - ["recompute-bigm", "dynamic"]
  - ["lagrange-default", "static"]
  - ["lagrange-default", "dynamic"],
  - ["lagrange-50", "static"]
  - ["lagrange-50", "dynamic"]
  - ["lagrange-100", "static"]
  - ["lagrange-100", "dynamic"]
  - ["lagrange-skip-30%", "static"]
  - ["lagrange-skip-30%", "dynamic"]
  - ["lagrange-skip-60%", "static"]
  - ["lagrange-skip-60%", "dynamic"]
  - ["lagrange-skip-90%", "static"]
  - ["lagrange-skip-90%", "dynamic"]
  - ["lagrange-skip-95%", "static"]
  - ["lagrange-skip-95%", "dynamic"]
  - ["mip-strong", "mip"]
  - ["mip-bigm", "mip"]

synth_small_sizes: [10, 14, 18, 22, 26, 30]
synth_small_fill_with:
  - [0.2, 1]
  - [0, 1]
synth_small_n_instances_per_size: 50

lagrange_sizes: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
lagrange_fill_with:
  - [0.2, 1]
  - [0, 1]
lagrange_n_instances_per_size: 5

synth_big_n_instances_per_size: 30
synth_big_sizes: # ["sizeRxsizeC", probably_row_or_col_in_sol_in_pct, timeout, first_n_instances_considered]
  - ["500x500", 5, 60, 30, 200]
  - ["500x500", 30, 60, 30, 200]
  - ["500x500", 70, 60, 30, 200]
  - ["1000x1000", 5, 60, 30, 200]
  - ["1000x1000", 30, 60, 30, 200]
  - ["1000x1000", 70, 60, 30, 200]
  - ["2000x2000", 5, 60, 30, 200]
  - ["2000x2000", 30, 60, 30, 200]
  - ["2000x2000", 70, 240, 30, 200]
