jarpath: "1MSS-assembly-0.1.jar"

ctr_methods:
  - ["nothing", "nothing"]
  - ["lpbound-fast-no-recompute-filter-row", "lpbound-fast-no-recompute-filter-row"]
  - ["lpbound-recompute", "lpbound-recompute"]
  - ["lagrange-best", "nothing"]
  - ["lagrange-best", "lagrange-best"]
  - ["lagrange-second", "nothing"]
  - ["lagrange-second", "lagrange-second"]

branch_methods:
  - static
  - dynamic

synth_small_sizes: [10, 15, 20, 25, 30, 35]
synth_small_fill_with:
  - [0.2, 1]
  - [0, 1]
synth_small_n_instances_per_size: 50

synth_big_n_instances_per_size: 50
synth_big_sizes: # ["sizeRxsizeC", probably_row_or_col_in_sol_in_pct, timeout, first_n_instances_considered]
  - ["300x300", 10, 60, 1]
